
/*
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by GenerateRCTThirdPartyFabricComponentsProviderH
 */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"

#import <React/RCTComponentViewProtocol.h>

#ifdef __cplusplus
extern "C" {
#endif

Class<RCTComponentViewProtocol> RCTThirdPartyFabricComponentsProvider(const char *name);
#if RCT_NEW_ARCH_ENABLED
#ifndef RCT_DYNAMIC_FRAMEWORKS


#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNKlarnaCheckoutViewCls(void) __attribute__((used)); // 1
Class<RCTComponentViewProtocol> RNKlarnaPaymentViewCls(void) __attribute__((used)); // 1
Class<RCTComponentViewProtocol> RNKlarnaStandaloneWebViewCls(void) __attribute__((used)); // 1
#endif

Class<RCTComponentViewProtocol> RNSVGCircleCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGClipPathCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGDefsCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGEllipseCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGFeColorMatrixCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGFeGaussianBlurCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGFeMergeCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGFeOffsetCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGFilterCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGForeignObjectCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGGroupCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGImageCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGSvgViewCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGLinearGradientCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGLineCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGMarkerCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGMaskCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGPathCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGPatternCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGRadialGradientCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGRectCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGSymbolCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGTextCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGTextPathCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGTSpanCls(void) __attribute__((used)); // 2
Class<RCTComponentViewProtocol> RNSVGUseCls(void) __attribute__((used)); // 2

#endif
#endif

#ifdef __cplusplus
}
#endif

#pragma GCC diagnostic pop

