
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/RNSentrySpec/EventEmitters.h>
#include <react/renderer/components/RNSentrySpec/Props.h>
#include <react/renderer/components/RNSentrySpec/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook::react {

JSI_EXPORT extern const char RNSentryReplayMaskComponentName[];

/*
 * `ShadowNode` for <RNSentryReplayMask> component.
 */
using RNSentryReplayMaskShadowNode = ConcreteViewShadowNode<
    RNSentryReplayMaskComponentName,
    RNSentryReplayMaskProps,
    RNSentryReplayMaskEventEmitter,
    RNSentryReplayMaskState>;

JSI_EXPORT extern const char RNSentryReplayUnmaskComponentName[];

/*
 * `ShadowNode` for <RNSentryReplayUnmask> component.
 */
using RNSentryReplayUnmaskShadowNode = ConcreteViewShadowNode<
    RNSentryReplayUnmaskComponentName,
    RNSentryReplayUnmaskProps,
    RNSentryReplayUnmaskEventEmitter,
    RNSentryReplayUnmaskState>;

} // namespace facebook::react
