// swift-tools-version:5.9
// swift-format-ignore-file

import Foundation
import PackageDescription

// BEGIN GENERATED by frameworkgen/build.sh render from frameworkgen/products.yml and the release
// artifacts (React Native 0.86.0). Do not edit by hand.
let version = "0.5.6"
let binaries: [(name: String, checksum: String)] = [
    ("HyperCore", "e2b95efc5357342e66c579ec31ecbf5f54d4ee95a9dcdf059f4581c8712ae9eb"),
    ("HyperOTA", "3d2b69fa429fb9291328ce2fe8105fe02fe69d48e606003f0299987d6f56c512"),
    ("Hyperswitch", "e010c3a86fe08c9217941ce442b8c44cb22a98418d3d4231e93f06b64146e5e3"),
    ("HyperswitchAirbornePlugin", "786bf645ada0ff21bcaabb43aba564b693fffe4b7a09eea9a2c01260074da927"),
    ("HyperswitchAuthentication", "82eba5225419c7e6669feaf85b1e72010e81644822bc9c8c031f74c65a4ae164"),
    ("HyperswitchAuthenticationNetcetera3DS", "3cdb4b7a5a4b994200b45c3661307f69139d5fdc28f3b829b7d2b0774e0f7db8"),
    ("HyperswitchAuthenticationTrident3DS", "c232ed928de244d6c9df3f1c6d3d7f5f49eb4b963726494d38b8eb29b9f7b446"),
    ("HyperswitchLite", "886a5f9eb4f73257be182c29f3d4840c6f32c1f5fe62e2c861da0abab1b77d79"),
    ("HyperswitchLiteScanCard", "a5124473a72f47351ff83666ed9f91aaa5ec831547456e1b9eef7aab6dabec52"),
    ("HyperswitchNetcetera3DSPlugin", "8fd841d58b0f698dd02480bd24d3ea0cfbb16b747f75fceb16df7ee8751aee83"),
    ("HyperswitchPayPalPlugin", "dddda4e259e787ed933877d43a8d8c655f2fa5b10602d15a5c11e26a16764c7a"),
    ("HyperswitchPaymentMethodManagement", "126d46d2f6128f0c1713d10c1b78b2bbc23f4097d046b159eb50a9ba6674e245"),
    ("HyperswitchPaymentMethods", "2b1acfc8101b7dfd5e43310248ee6bf77d246e3eef3b84cf355c05ebc04723da"),
    ("HyperswitchReactNative", "91d5e27342474915e15e8454073859dd4c707357fbe88f9d7375454fff8ea05b"),
    ("HyperswitchScanCard", "02b3b720ffb02ed5349b1955ab780f3eafdcafb9f031e6799114cf42b4323c13"),
    ("HyperswitchScanCardPlugin", "2e396c648932316d3151a95d9ce890ccde1c28e57b322973c620c6caf0d9c582"),
    ("HyperswitchSentryPlugin", "4699a46a3edf14adeec40854abe6f2ece2f846b3b12a776a5231c7539d8319ab"),
    ("HyperswitchShared", "af114239cfd2c7fd0dec77045920744b51bb851a8463cdd2ae643095c0024e49"),
    ("React", "a4f9fc0cbaecdef44efb86eaf0b355af4a75a73c3284a23e0ae835a4c6193ccc"),
    ("ReactNativeDependencies", "63923e0a07cbd23949f40978c713cc7bca5ff24ec8c5cee03668f05cefd0a29e"),
    ("ThreeDS_SDK", "cdeed1d9dd6acfcaa9bbcc58c8fc5ed79bd41129b343928db2221630fedb3794"),
    ("Trident", "6f5ea4d4665e611df0c8f572fe223881ae0ddde18b605545313972f7313f2a6c"),
    ("hermesvm", "964c53edc3422e9b7de35e3b6419813172fe3b6c12f227a1d777496874af4052"),
]
let products: [(name: String, targets: [String])] = [
    ("Hyperswitch", ["HyperswitchShared", "HyperswitchReactNative", "Hyperswitch", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchPaymentMethods", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPaymentMethods", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchPaymentMethodManagement", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPaymentMethodManagement", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchScanCard", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchScanCardPlugin", "HyperswitchScanCard", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchNetcetera3DS", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchNetcetera3DSPlugin", "React", "ReactNativeDependencies", "ThreeDS_SDK", "hermesvm"]),
    ("HyperswitchPayPal", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPayPalPlugin", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchSentry", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchSentryPlugin", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchAirborne", ["HyperswitchShared", "HyperswitchAirbornePlugin", "HyperCore", "HyperOTA"]),
    ("HyperswitchLite", ["HyperswitchShared", "HyperswitchLite"]),
    ("HyperswitchLiteScanCard", ["HyperswitchShared", "HyperswitchLite", "HyperswitchLiteScanCard", "HyperswitchScanCard"]),
    ("HyperswitchAuthentication", ["HyperswitchShared", "HyperswitchAuthentication"]),
    ("HyperswitchAuthenticationNetcetera3DS", ["HyperswitchShared", "HyperswitchAuthentication", "HyperswitchAuthenticationNetcetera3DS", "ThreeDS_SDK"]),
    ("HyperswitchAuthenticationTrident3DS", ["HyperswitchShared", "HyperswitchAuthentication", "HyperswitchAuthenticationTrident3DS", "Trident"]),
]
// END GENERATED

let localArtifacts = FileManager.default.fileExists(atPath: Context.packageDirectory + "/build/artifacts/.local")

func binaryTarget(_ name: String, checksum: String) -> Target {
    if localArtifacts {
        return .binaryTarget(name: name, path: "build/artifacts/\(name).xcframework")
    }
    return .binaryTarget(
        name: name,
        url: "https://github.com/juspay/hyperswitch-sdk-ios/releases/download/v\(version)/\(name).xcframework.zip",
        checksum: checksum
    )
}

let package = Package(
    name: "Hyperswitch",
    platforms: [.iOS("15.1")],
    products: products.map { .library(name: $0.name, targets: $0.targets) },
    targets: binaries.map { binaryTarget($0.name, checksum: $0.checksum) }
)
