// swift-tools-version:5.9
// swift-format-ignore-file

import Foundation
import PackageDescription

// BEGIN GENERATED by frameworkgen/build.sh render from frameworkgen/products.yml and the release
// artifacts (React Native 0.86.0). Do not edit by hand.
let version = "0.5.6"
let binaries: [(name: String, checksum: String)] = [
    ("HyperCore", "ce19d2fa9a8acbb983df690e7d7fd31932e1d675799f140e907f9556ab52cfe9"),
    ("HyperOTA", "45d4b2ba30034f5a378dab5570224b92dac5527dd1ef96b91d17dbdb861ccb9c"),
    ("Hyperswitch", "9d5b6aec216a8539b88c86df1e28550cefcd304403a736c682f28ab3da869feb"),
    ("HyperswitchAirbornePlugin", "a4e44601d55485ee43297a03cc290470fab2b189b45510ea2b7b255a0db712a9"),
    ("HyperswitchAuthentication", "199587e310da0bfff07d3056a13d2a430466c0efd07b1446ce98409df257f491"),
    ("HyperswitchAuthenticationNetcetera3DS", "83c0e46e1de6dffe9ea95886535a6f42af3a31eca95f9135eb81dc8f82827f4e"),
    ("HyperswitchLite", "a07ab533cc3603ca701145339c769e984fa4ed5611be7f7be2a7f1efcbaff5a8"),
    ("HyperswitchNetcetera3DSPlugin", "6b2b583426100dbc47414c6da03eb659573fbfad49c99d8ed6acdcd1af6134a1"),
    ("HyperswitchPayPalPlugin", "170d3d115eb4a7993251cc1a0c3ee3fd961b6f2442acf0c3e3d0208193cbfbeb"),
    ("HyperswitchPaymentMethodManagement", "1d11db4ec130c73ed269341e7ea0ca9d178d681a003839f834cd1d4e9c370ff6"),
    ("HyperswitchPaymentMethods", "6ae3b19936afedff6b0fb69b6dd7223e4d022c59e128a4325f96156e2994ad21"),
    ("HyperswitchReactNative", "07aeaee41d1b0ae2dee52cb71dbb9ebd5ca24b45b1fecc6ac2b4acf239a41774"),
    ("HyperswitchScanCard", "a4133fae26e74dfba3b2133859a3039a9fbc9f7eff92fb285ff1b7cbb5f2452e"),
    ("HyperswitchScanCardPlugin", "1d36e7a6d249af7734635694484cce93793da3bc0b66dcedf510c94dd38c7788"),
    ("HyperswitchSentryPlugin", "adc437ed694ecb230666385d97a9c511add1d94c8b35d0de8b856cdb104f06b3"),
    ("HyperswitchShared", "3cba4282f4825b3319916802f3daaac2462f1651aed17e423557771bef608a45"),
    ("React", "4254bda8f9f1a4c43d7fc3c5f94bdf322b4ebd9aa62856e1f2af644c8a727896"),
    ("ReactNativeDependencies", "bf542d1b2ed2621db6039be6df87ed99c21706bb3d7c832c23949881257fcc41"),
    ("ThreeDS_SDK", "e7c12e79dc0ed13365d9891db45af324751be31f48c621898898728dfbb2af26"),
    ("hermesvm", "b59182f1144b47d18fd119a4e046b55c34b01d8316c6cbec2938fa68a1a80764"),
]
let products: [(name: String, targets: [String])] = [
    ("Hyperswitch", ["HyperswitchShared", "HyperswitchReactNative", "Hyperswitch", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchPaymentMethods", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPaymentMethods", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchPaymentMethodManagement", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPaymentMethodManagement", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchScanCard", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchScanCardPlugin", "HyperswitchScanCard", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchNetcetera3DS", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchNetcetera3DSPlugin", "React", "ReactNativeDependencies", "ThreeDS_SDK", "hermesvm"]),
    ("HyperswitchPayPal", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPayPalPlugin", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchSentry", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchSentryPlugin", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchAirborne", ["HyperswitchShared", "HyperswitchAirbornePlugin", "HyperCore", "HyperOTA"]),
    ("HyperswitchLite", ["HyperswitchShared", "HyperswitchLite"]),
    ("HyperswitchAuthentication", ["HyperswitchShared", "HyperswitchAuthentication"]),
    ("HyperswitchAuthenticationNetcetera3DS", ["HyperswitchShared", "HyperswitchAuthentication", "HyperswitchAuthenticationNetcetera3DS", "ThreeDS_SDK"]),
]
// END GENERATED

let localArtifacts = FileManager.default.fileExists(atPath: Context.packageDirectory + "/build/artifacts/.local")

func binaryTarget(_ name: String, checksum: String) -> Target {
    if localArtifacts {
        return .binaryTarget(name: name, path: "build/artifacts/\(name).xcframework")
    }
    return .binaryTarget(
        name: name,
        url: "https://github.com/juspay/hyperswitch-sdk-ios/releases/download/v\(version)/\(name).xcframework.zip",
        checksum: checksum
    )
}

let package = Package(
    name: "Hyperswitch",
    platforms: [.iOS("15.1")],
    products: products.map { .library(name: $0.name, targets: $0.targets) },
    targets: binaries.map { binaryTarget($0.name, checksum: $0.checksum) }
)
