// swift-tools-version:5.9
// swift-format-ignore-file

import Foundation
import PackageDescription

// BEGIN GENERATED by frameworkgen/build.sh render from frameworkgen/products.yml and the release
// artifacts (React Native 0.86.0). Do not edit by hand.
let version = "0.5.6"
let binaries: [(name: String, checksum: String)] = [
    ("HyperCore", "bc99aec95d620f51c7edbde132d8a5aa80af62d8a3bcee69c90c5cc1cb5ad614"),
    ("HyperOTA", "aa9e690da9d81789c6702631580ad06786f0ba83333c27f47702ec6e4eb412f9"),
    ("Hyperswitch", "d3b132651d9b926c3a4955e637a378655b741b2f03746cbbb5dab73381e7449c"),
    ("HyperswitchAirbornePlugin", "e89356ea55a9f2dd165ab1721693835f8e90fd7fd93153842f848b9e926ac595"),
    ("HyperswitchAuthentication", "77bbb96e751d05f5ee6abbda6d1d80d40f09d047f59817911ad0bb3a9e1ac5a7"),
    ("HyperswitchAuthenticationNetcetera3DS", "43edc1e27ffd986be9204f7db6bb8e664da01cbb0933e27819a4f0d775191ce4"),
    ("HyperswitchAuthenticationTrident3DS", "ee918cb7c557f19e54879a81097b640af52fb3cac1bd1ad70f88d2db66a1b31b"),
    ("HyperswitchLite", "069b68cd6eaa44133d35f6d8fe4ee1e8ca27b4220a6c93b9e456ff70ce8013ac"),
    ("HyperswitchLiteScanCard", "f110eafc2fdc8e0a91b964be7ae3cbd6ccdea7c16a896f7e1fc327592d7da843"),
    ("HyperswitchNetcetera3DSPlugin", "92ae88cdaccb12641073d4ce6305cc31e5a12acac84bb9fa49ddf05006f227d4"),
    ("HyperswitchPayPalPlugin", "8ff7560e94ccf1325d878b8570cd18851542a6a7e13966271d148abd510e6023"),
    ("HyperswitchPaymentMethodManagement", "1d3292972714cebd88de7e72df25c2b34daf0cddc7e9495bd0edf7ed0eaf1093"),
    ("HyperswitchPaymentMethods", "a02948e1c2ac407f72109286345b4eb7c762a6c4667c56c06c20e1be251c2d40"),
    ("HyperswitchReactNative", "2cb173c0275666161280081d0bd88b00620a509802d5522d6da7aaee238925c2"),
    ("HyperswitchScanCard", "b6c663d2b565209d92ded44bc1ddcb544faad1f2a848d4c6e4001b183bb393bb"),
    ("HyperswitchScanCardPlugin", "08370895bce0dc89253fd671160131bbc1cb2443ba1c16adf32be8f885e8d981"),
    ("HyperswitchSentryPlugin", "aae9b9e4dddcaa208368f61f6fb22e6ab2be382a572611dbcdb22b7b8ec1ff72"),
    ("HyperswitchShared", "41ad5dff0c1cbc65d37de8749c25237c90320372c0b46a960e2b5cf51d34b2a7"),
    ("React", "81cf55b1d02ba00cd935ca428c5265cb7d6c57d2375393b888207ca34b17e241"),
    ("ReactNativeDependencies", "d01d307700e346a02b04452f650e641c6b6f1038e7898d52dbe72f7db35f06cb"),
    ("ThreeDS_SDK", "4959af89b535bf05454d8ddc1a74b8fd6fa2f505585f46a24644a873b214c3d2"),
    ("Trident", "8145f69af0637171c3074e6002c0a1fa2d0c409e2b2cff50a6db76b8df7e0b9e"),
    ("hermesvm", "0997aeb12bec473234d7d60a3c5da1c4fb209f7c9817dd63d36d237e9e307ddb"),
]
let products: [(name: String, targets: [String])] = [
    ("Hyperswitch", ["HyperswitchShared", "HyperswitchReactNative", "Hyperswitch", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchPaymentMethods", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPaymentMethods", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchPaymentMethodManagement", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPaymentMethodManagement", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchScanCard", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchScanCardPlugin", "HyperswitchScanCard", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchNetcetera3DS", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchNetcetera3DSPlugin", "React", "ReactNativeDependencies", "ThreeDS_SDK", "hermesvm"]),
    ("HyperswitchPayPal", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchPayPalPlugin", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchSentry", ["HyperswitchShared", "HyperswitchReactNative", "HyperswitchSentryPlugin", "React", "ReactNativeDependencies", "hermesvm"]),
    ("HyperswitchAirborne", ["HyperswitchShared", "HyperswitchAirbornePlugin", "HyperCore", "HyperOTA"]),
    ("HyperswitchLite", ["HyperswitchShared", "HyperswitchLite"]),
    ("HyperswitchLiteScanCard", ["HyperswitchShared", "HyperswitchLite", "HyperswitchLiteScanCard", "HyperswitchScanCard"]),
    ("HyperswitchAuthentication", ["HyperswitchShared", "HyperswitchAuthentication"]),
    ("HyperswitchAuthenticationNetcetera3DS", ["HyperswitchShared", "HyperswitchAuthentication", "HyperswitchAuthenticationNetcetera3DS", "ThreeDS_SDK"]),
    ("HyperswitchAuthenticationTrident3DS", ["HyperswitchShared", "HyperswitchAuthentication", "HyperswitchAuthenticationTrident3DS", "Trident"]),
]
// END GENERATED

let localArtifacts = FileManager.default.fileExists(atPath: Context.packageDirectory + "/build/artifacts/.local")

func binaryTarget(_ name: String, checksum: String) -> Target {
    if localArtifacts {
        return .binaryTarget(name: name, path: "build/artifacts/\(name).xcframework")
    }
    return .binaryTarget(
        name: name,
        url: "https://github.com/juspay/hyperswitch-sdk-ios/releases/download/v\(version)/\(name).xcframework.zip",
        checksum: checksum
    )
}

let package = Package(
    name: "Hyperswitch",
    platforms: [.iOS("15.1")],
    products: products.map { .library(name: $0.name, targets: $0.targets) },
    targets: binaries.map { binaryTarget($0.name, checksum: $0.checksum) }
)
