# Rewrites the generated block of Package.swift (between `// BEGIN GENERATED` and
# `// END GENERATED`): the version, every binary artifact with its checksum, and each product's
# binary targets, from products.yml, runtime.json and build/dist/artifacts.json.
require_relative 'frameworkgen'
include FrameworkGen

manifest = File.join(IOS, 'Package.swift')
dist = File.join(DIST, 'artifacts.json')
abort "#{dist} is missing: run package first" unless File.exist?(dist)
artifacts = JSON.parse(File.read(dist))

binaries = artifacts.fetch('artifacts')
# A product lists every binary it ships (SPM binary targets cannot depend on each other).
product_targets = products.keys.to_h do |product|
  targets = product_contents(product)
  missing = targets - binaries.keys
  abort "product #{product} needs #{missing.join(', ')}, which build/dist lacks" unless missing.empty?
  [product, targets]
end

quote = ->(values) { values.map { |value| "\"#{value}\"" }.join(', ') }
generated = <<~SWIFT
  // BEGIN GENERATED by frameworkgen/build.sh render from frameworkgen/products.yml and the release
  // artifacts (React Native #{artifacts.fetch('reactNative')}). Do not edit by hand.
  let version = "#{artifacts.fetch('version')}"
  let binaries: [(name: String, checksum: String)] = [
  #{binaries.map { |name, info| "    (\"#{name}\", \"#{info.fetch('checksum')}\")," }.join("\n")}
  ]
  let products: [(name: String, targets: [String])] = [
  #{product_targets.map { |product, targets| "    (\"#{product}\", [#{quote.(targets)}])," }.join("\n")}
  ]
  // END GENERATED
SWIFT

text = File.read(manifest)
pattern = %r{^// BEGIN GENERATED.*?^// END GENERATED\n}m
abort "#{manifest} has no generated block" unless text.match?(pattern)
File.write(manifest, text.sub(pattern, generated))
puts "rendered #{manifest}: #{binaries.size} binaries, #{product_targets.size} products, version #{artifacts.fetch('version')}"
