
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>

namespace facebook::react {

class RNKlarnaCheckoutViewProps final : public ViewProps {
 public:
  RNKlarnaCheckoutViewProps() = default;
  RNKlarnaCheckoutViewProps(const PropsParserContext& context, const RNKlarnaCheckoutViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string returnUrl{};
};

class RNKlarnaPaymentViewProps final : public ViewProps {
 public:
  RNKlarnaPaymentViewProps() = default;
  RNKlarnaPaymentViewProps(const PropsParserContext& context, const RNKlarnaPaymentViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string category{};
  std::string returnUrl{};
};

class RNKlarnaStandaloneWebViewProps final : public ViewProps {
 public:
  RNKlarnaStandaloneWebViewProps() = default;
  RNKlarnaStandaloneWebViewProps(const PropsParserContext& context, const RNKlarnaStandaloneWebViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string returnUrl{};
  std::string overScrollMode{};
  bool bounces{false};
};

} // namespace facebook::react
