
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/RNKlarnaMobileSDK/EventEmitters.h>
#include <react/renderer/components/RNKlarnaMobileSDK/Props.h>
#include <react/renderer/components/RNKlarnaMobileSDK/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook::react {

JSI_EXPORT extern const char RNKlarnaCheckoutViewComponentName[];

/*
 * `ShadowNode` for <RNKlarnaCheckoutView> component.
 */
using RNKlarnaCheckoutViewShadowNode = ConcreteViewShadowNode<
    RNKlarnaCheckoutViewComponentName,
    RNKlarnaCheckoutViewProps,
    RNKlarnaCheckoutViewEventEmitter,
    RNKlarnaCheckoutViewState>;

JSI_EXPORT extern const char RNKlarnaPaymentViewComponentName[];

/*
 * `ShadowNode` for <RNKlarnaPaymentView> component.
 */
using RNKlarnaPaymentViewShadowNode = ConcreteViewShadowNode<
    RNKlarnaPaymentViewComponentName,
    RNKlarnaPaymentViewProps,
    RNKlarnaPaymentViewEventEmitter,
    RNKlarnaPaymentViewState>;

JSI_EXPORT extern const char RNKlarnaStandaloneWebViewComponentName[];

/*
 * `ShadowNode` for <RNKlarnaStandaloneWebView> component.
 */
using RNKlarnaStandaloneWebViewShadowNode = ConcreteViewShadowNode<
    RNKlarnaStandaloneWebViewComponentName,
    RNKlarnaStandaloneWebViewProps,
    RNKlarnaStandaloneWebViewEventEmitter,
    RNKlarnaStandaloneWebViewState>;

} // namespace facebook::react
