/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

#ifdef ANDROID
#include <folly/dynamic.h>
#endif

namespace facebook::react {

class RNKlarnaCheckoutViewState {
public:
  RNKlarnaCheckoutViewState() = default;

#ifdef ANDROID
  RNKlarnaCheckoutViewState(RNKlarnaCheckoutViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
#endif
};

class RNKlarnaPaymentViewState {
public:
  RNKlarnaPaymentViewState() = default;

#ifdef ANDROID
  RNKlarnaPaymentViewState(RNKlarnaPaymentViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
#endif
};

class RNKlarnaStandaloneWebViewState {
public:
  RNKlarnaStandaloneWebViewState() = default;

#ifdef ANDROID
  RNKlarnaStandaloneWebViewState(RNKlarnaStandaloneWebViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
#endif
};

} // namespace facebook::react